services:
  backend:
    build: ./backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: milionerzy
    volumes:
      - pgdata:/var/lib/postgresql/data 
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: unkor00t@gmail.com
      PGADMIN_DEFAULT_PASSWORD: abc123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgdata:
  pgadmin-data:
  backend:
  frontend: